# Exercise 2 - National Budget

In [176]:
import pandas as pd

In [177]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('national-budget.csv')
df.head()

,שנה,קוד רמה 1,שם רמה 1,קוד ושם רמה 1,קוד רמה 2,שם רמה 2,קוד ושם רמה 2,קוד סוג סעיף,שם סוג סעיף,קוד סעיף,שם סעיף,קוד ושם סעיף,קוד תחום,שם תחום,קוד ושם תחום,קוד תכנית,שם תכנית,קוד ושם תכנית,קוד תקנה,שם תקנה,קוד ושם תקנה,קוד מיון רמה 1,שם מיון רמה 1,קוד ושם מיון רמה 1,קוד מיון רמה 2,שם מיון רמה 2,קוד ושם מיון רמה 2,הוצאה/הכנסה,פשח,סוג תקציב,הוצאה נטו,הוצאה מותנית בהכנסה,הכנסה מיועדת,הרשאה להתחייב,שיא כח אדם,עבצ,כמות,יתרת התחיבויות,תקציב קורונה
0,1997,1,בטחון וסדר ציבורי,1-בטחון וסדר ציבורי,11,בטחון,11-בטחון,1.0,תקציב רגיל,15.0,משרד הבטחון,15 -משרד הבטחון,1501.0,בטחון,1501 -בטחון,150101.0,בטחון,150101 -בטחון,15010101.0,שכר,15010101-שכר,1.0,שכר,001-שכר,30.0,שכר בארץ,030-שכר בארץ,הוצאה,0.0,ביצוע,5548100.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1,1997,1,בטחון וסדר ציבורי,1-בטחון וסדר ציבורי,11,בטחון,11-בטחון,1.0,תקציב רגיל,15.0,משרד הבטחון,15 -משרד הבטחון,1501.0,בטחון,1501 -בטחון,150101.0,בטחון,150101 -בטחון,15010101.0,שכר,15010101-שכר,1.0,שכר,001-שכר,30.0,שכר בארץ,030-שכר בארץ,הוצאה,0.0,מאושר,10262268.0,0.0,0.0,0.0,2022.5,0.0,0.0,NaN,NaN
2,1997,1,בטחון וסדר ציבורי,1-בטחון וסדר ציבורי,11,בטחון,11-בטחון,1.0,תקציב רגיל,15.0,משרד הבטחון,15 -משרד הבטחון,1501.0,בטחון,1501 -בטחון,150101.0,בטחון,150101 -בטחון,15010101.0,שכר,15010101-שכר,1.0,שכר,001-שכר,30.0,שכר בארץ,030-שכר בארץ,הוצאה,0.0,מקורי,10142268.0,0.0,0.0,0.0,2021.5,0.0,0.0,NaN,NaN
3,1997,1,בטחון וסדר ציבורי,1-בטחון וסדר ציבורי,11,בטחון,11-בטחון,1.0,תקציב רגיל,15.0,משרד הבטחון,15 -משרד הבטחון,1501.0,בטחון,1501 -בטחון,150101.0,בטחון,150101 -בטחון,15010102.0,הכנסות מגורמי חוץ,15010102-הכנסות מגורמי חוץ,4.0,הכנסות מיועדות,004-הכנסות מיועדות,41.0,הכנסות תקציב רגיל,041-הכנסות תקציב רגיל,הכנסה,0.0,ביצוע,-682300.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
4,1997,1,בטחון וסדר ציבורי,1-בטחון וסדר ציבורי,11,בטחון,11-בטחון,1.0,תקציב רגיל,15.0,משרד הבטחון,15 -משרד הבטחון,1501.0,בטחון,1501 -בטחון,150101.0,בטחון,150101 -בטחון,15010102.0,הכנסות מגורמי חוץ,15010102-הכנסות מגורמי חוץ,4.0,הכנסות מיועדות,004-הכנסות מיועדות,41.0,הכנסות תקציב רגיל,041-הכנסות תקציב רגיל,הכנסה,0.0,מאושר,0.0,0.0,-1744374.0,0.0,0.0,0.0,0.0,NaN,NaN

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975975 entries, 0 to 975974
Data columns (total 39 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   שנה                  975975 non-null  int64
 1   קוד רמה 1            975975 non-null  int64
 2   שם רמה 1             975975 non-null  object
 3   קוד ושם רמה 1        975975 non-null  object
 4   קוד רמה 2            975975 non-null  int64
 5   שם רמה 2             975975 non-null  object
 6   קוד ושם רמה 2        975975 non-null  object
 7   קוד סוג סעיף         975935 non-null  float64
 8   שם סוג סעיף          975935 non-null  object
 9   קוד סעיף             975935 non-null  float64
 10  שם סעיף              975932 non-null  object
 11  קוד ושם סעיף         975935 non-null  object
 12  קוד תחום             975935 non-null  float64
 13  שם תחום              975932 non-null  object
 14  קוד ושם תחום         975935 non-null  object
 15  קוד תכנית            975935 non-null  float64
 16  שם תכנית             975932 non-null  object
 17  קוד ושם תכנית        975935 non-null  object
 18  קוד תקנה             975935 non-null  float64
 19  שם תקנה              975923 non-null  object
 20  קוד ושם תקנה         975935 non-null  object
 21  קוד מיון רמה 1       975935 non-null  float64
 22  שם מיון רמה 1        975935 non-null  object
 23  קוד ושם מיון רמה 1   975935 non-null  object
 24  קוד מיון רמה 2       975935 non-null  float64
 25  שם מיון רמה 2        975935 non-null  object
 26  קוד ושם מיון רמה 2   975935 non-null  object
 27  הוצאה/הכנסה          975935 non-null  object
 28  פשח                  975935 non-null  float64
 29  סוג תקציב            975975 non-null  object
 30  הוצאה נטו            929058 non-null  float64
 31  הוצאה מותנית בהכנסה  654386 non-null  float64
 32  הכנסה מיועדת         654386 non-null  float64
 33  הרשאה להתחייב        929018 non-null  float64
 34  שיא כח אדם           973869 non-null  float64
 35  עבצ                  974459 non-null  float64
 36  כמות                 931934 non-null  float64
 37  יתרת התחיבויות       274632 non-null  float64
 38  תקציב קורונה         0 non-null       float64
dtypes: float64(17), int64(3), object(19)
memory usage: 290.4+ MB

### Question 1 - Yearly Budget

In [179]:
def education_budget(df, year: int) -> int:
    """
    Calculates education budget per year by filtering all
    rows where the income/expense flag is marked expense
    and the office category name is "Education"

    :param df: National budget dataframe
    :param year: The desired year to calculate
    :return: Education budget per the desired year
    """
    df = df[(df['שנה'] == year) 
        & (df['הוצאה/הכנסה'] == 'הוצאה') 
        & (df['שם סעיף'].str.contains('חינוך'))]
    return int(df['הוצאה נטו'].sum())
    
education_budget(df, 1997)

57987549

### Question 2 - Defense Budget Percentage

In [180]:
def security_budget_ratio(df, year) -> float:
    """
    Calculates security budget percentage when compared to other offices.
    We sum all the expenses of the government and divide them by the
    expenses of the security budget as calculated in the former function

    :param df: National budget dataframe
    :param year: The desired year
    :return: Yearly security budget ratio
    """
    df = df[df['שנה'] == year]
    total_year_sum = df['הוצאה נטו'].sum()
    df = df[(df['הוצאה/הכנסה'] == 'הוצאה') 
        & (df['שם סעיף'] == 'משרד הבטחון')]
    return df['הוצאה נטו'].sum() / total_year_sum * 100

security_budget_ratio(df, 1997)

8.657693633613357

### Question 3 - Largest Yearly Budget

In [181]:
def largest_budget_year(df, office: str) -> int:
    """
    Calculates largest office budget ever by name. First we filter out the
    chosen office by name, we iterate over the unique year values in the dataframe
    and sum each year expenses accordingly. At the end we return the
    maximum calculated value

    :param df: National budget dataframe
    :param office: Office name
    :return: Largest chosen office budget ever
    """
    df = df[df['שם סעיף'] == office]
    yearly_budget = {}
    for year in df['שנה'].unique():
        yearly_budget[year] = df[df['שנה'] == year]['הוצאה נטו'].sum()
    years = yearly_budget.values()
    return int(max(years))

largest_budget_year(df, 'משרד הבטחון')

198461009

### Question 4 - Average Salary Per Ministry

In [182]:
def avg_office_salary_per_year(df, office, year) -> float:
    """
    Returns the average worker salary/expense for a specific 
    office in a specific year by calculating total salary expenses 
    in a certain year and dividing by the number of workers
    """
    df = df[(df['שם סעיף'] == office) 
            & (df['שם מיון רמה 1'] == 'שכר')
            & (df['שנה'] == year)]
    return round(df['הוצאה נטו'].sum() / df['שיא כח אדם'].max(), 3)

avg_office_salary_per_year(df, 'משרד הבטחון', 1997)

14537.009